"""
Django settings for attendancesystem project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v3*=uz-@a*lt-#p@!xcd*6j21@*l-zf+jm71f!!@5pqn+euy97"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'attendancesystem.settings')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'crispy_forms',
    'django_extensions',
    'attendance',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "attendancesystem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "attendancesystem.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
        'default': dj_database_url.config(
        default='mysql://root:shot-010907@localhost:3306/attendance_db'
    )
    # "default": {
    #     # "ENGINE" : 'django.db.backends.mysql',
    #     # # "NAME" : 'attendance_db',
    #     # # "USER" : 'root',
    #     # # "PASSWORD" : 'shot-010907',
    #     # "HOST" : 'localhost',
    #     # # "PORT" : '3306',
    #     # # "OPTIONS" : {
    #     # #     'autocommit': True
    #     # # }
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"



MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"    

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'attendance.User'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

FACE_RECOGNITION_TOLERANCE = 0.6
FACE_DATA_DIR = os.path.join(BASE_DIR, 'face_data')
CASCADES_DIR = os.path.join(BASE_DIR, 'cascades')


REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_RATES': {
        'face_detection': '5/second',  # Limit to 5 requests per second
    }
}

# Authentication backends
AUTHENTICATION_BACKENDS = ['attendance.auth_backends.EmailBackend']

"""
SmartFace Settings Module

This module contains configuration settings for the SmartFace attendance system.
These settings can be imported and used throughout the application.
"""

# Face Recognition Settings
FACE_RECOGNITION_TOLERANCE = 0.6  
FACE_RECOGNITION_MODEL = 'vggface2'  

# AI Message Settings
ENABLE_AI_MESSAGES = True  
AI_MESSAGE_CACHE_TIMEOUT = 3600  

# Attendance Settings
LATE_CUTOFF_TIME = '09:30'  
MINIMUM_WORK_HOURS = 8

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'smartfaceunity@gmail.com'
EMAIL_HOST_PASSWORD = 'mboy jbeo sicr nqjt'  
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER